<?php

require_once __DIR__ . '/../utils/reqrep.php';
require_once __DIR__ . '/../storage/themes.php';

function onSaveTheme($args) {

    $mysqli = dbConnect();

    $themes = selectTheme($mysqli, $args->themeName);
    if( !$themes ) {
        $id = insertTheme($mysqli, [
            sqlString($mysqli,$args->themeName),
            sqlString($mysqli,$args->theme->appBg),
            sqlString($mysqli,$args->theme->appFg),
            sqlString($mysqli,$args->theme->appFont),
            sqlString($mysqli,$args->theme->appFsize),
            sqlString($mysqli,$args->theme->appWidth),
            sqlString($mysqli,$args->theme->appRadius),
            sqlString($mysqli,$args->theme->appFolder),
            sqlString($mysqli,$args->theme->editBg),
            sqlString($mysqli,$args->theme->editFg),
            sqlString($mysqli,$args->theme->editActBg),
            sqlString($mysqli,$args->theme->editActFg),
            sqlString($mysqli,$args->theme->editBdFg),
            sqlString($mysqli,$args->theme->editBdW),
            sqlString($mysqli,$args->theme->toolBg),
            sqlString($mysqli,$args->theme->toolFg),
            sqlString($mysqli,$args->theme->toolActBg),
            sqlString($mysqli,$args->theme->toolActFg),
            sqlString($mysqli,$args->theme->toolBdFg),
            sqlString($mysqli,$args->theme->toolBdW),
            sqlString($mysqli,$args->theme->toolShadow),
            sqlString($mysqli,$args->theme->titleBg),
            sqlString($mysqli,$args->theme->titleFg),
            sqlString($mysqli,$args->theme->titleBdFg),
            sqlString($mysqli,$args->theme->titleBdW),
            sqlString($mysqli,$args->theme->titleShadow),
            sqlString($mysqli,$args->theme->barBg),
            sqlString($mysqli,$args->theme->barFg),
            sqlString($mysqli,$args->theme->barActBg),
            sqlString($mysqli,$args->theme->barActFg),
            sqlString($mysqli,$args->theme->barBdFg),
            sqlString($mysqli,$args->theme->barBdW),
            sqlString($mysqli,$args->theme->barShadow),
            sqlString($mysqli,$args->theme->blockBg),
            sqlString($mysqli,$args->theme->blockFg),
            sqlString($mysqli,$args->theme->blockActBg),
            sqlString($mysqli,$args->theme->blockActFg),
            sqlString($mysqli,$args->theme->blockBdFg),
            sqlString($mysqli,$args->theme->blockBdW),
            sqlString($mysqli,$args->theme->blockShadow),
            sqlString($mysqli,$args->theme->formBg),
            sqlString($mysqli,$args->theme->formFg),
            sqlString($mysqli,$args->theme->formBdFg),
            sqlString($mysqli,$args->theme->formBdW),
            sqlString($mysqli,$args->theme->formShadow),
            sqlString($mysqli,$args->theme->btnBg),
            sqlString($mysqli,$args->theme->btnFg),
            sqlString($mysqli,$args->theme->btnActBg),
            sqlString($mysqli,$args->theme->btnActFg),
            sqlString($mysqli,$args->theme->btnBdFg),
            sqlString($mysqli,$args->theme->btnBdW),
            sqlString($mysqli,$args->theme->btnShadow),
            sqlString($mysqli,$args->theme->inpBg),
            sqlString($mysqli,$args->theme->inpFg),
            sqlString($mysqli,$args->theme->inpActBg),
            sqlString($mysqli,$args->theme->inpActFg),
            sqlString($mysqli,$args->theme->inpBdFg),
            sqlString($mysqli,$args->theme->inpBdW),
            sqlString($mysqli,$args->theme->inpShadow),
            sqlString($mysqli,$args->theme->linkBg),
            sqlString($mysqli,$args->theme->linkFg),
            sqlString($mysqli,$args->theme->linkActBg),
            sqlString($mysqli,$args->theme->linkActFg)
        ]);
        dbDisonnect($mysqli);
        return new Reply($id>0?'ok':'error', $id > 0 );
    }
    else {
        $result = updateTheme($mysqli, $args->themeName, [
            sqlString($mysqli,$args->theme->appBg),
            sqlString($mysqli,$args->theme->appFg),
            sqlString($mysqli,$args->theme->appFont),
            sqlString($mysqli,$args->theme->appFsize),
            sqlString($mysqli,$args->theme->appWidth),
            sqlString($mysqli,$args->theme->appRadius),
            sqlString($mysqli,$args->theme->appFolder),
            sqlString($mysqli,$args->theme->editBg),
            sqlString($mysqli,$args->theme->editFg),
            sqlString($mysqli,$args->theme->editActBg),
            sqlString($mysqli,$args->theme->editActFg),
            sqlString($mysqli,$args->theme->editBdFg),
            sqlString($mysqli,$args->theme->editBdW),
            sqlString($mysqli,$args->theme->toolBg),
            sqlString($mysqli,$args->theme->toolFg),
            sqlString($mysqli,$args->theme->toolActBg),
            sqlString($mysqli,$args->theme->toolActFg),
            sqlString($mysqli,$args->theme->toolBdFg),
            sqlString($mysqli,$args->theme->toolBdW),
            sqlString($mysqli,$args->theme->toolShadow),
            sqlString($mysqli,$args->theme->titleBg),
            sqlString($mysqli,$args->theme->titleFg),
            sqlString($mysqli,$args->theme->titleBdFg),
            sqlString($mysqli,$args->theme->titleBdW),
            sqlString($mysqli,$args->theme->titleShadow),
            sqlString($mysqli,$args->theme->barBg),
            sqlString($mysqli,$args->theme->barFg),
            sqlString($mysqli,$args->theme->barActBg),
            sqlString($mysqli,$args->theme->barActFg),
            sqlString($mysqli,$args->theme->barBdFg),
            sqlString($mysqli,$args->theme->barBdW),
            sqlString($mysqli,$args->theme->barShadow),
            sqlString($mysqli,$args->theme->blockBg),
            sqlString($mysqli,$args->theme->blockFg),
            sqlString($mysqli,$args->theme->blockActBg),
            sqlString($mysqli,$args->theme->blockActFg),
            sqlString($mysqli,$args->theme->blockBdFg),
            sqlString($mysqli,$args->theme->blockBdW),
            sqlString($mysqli,$args->theme->blockShadow),
            sqlString($mysqli,$args->theme->formBg),
            sqlString($mysqli,$args->theme->formFg),
            sqlString($mysqli,$args->theme->formBdFg),
            sqlString($mysqli,$args->theme->formBdW),
            sqlString($mysqli,$args->theme->formShadow),
            sqlString($mysqli,$args->theme->btnBg),
            sqlString($mysqli,$args->theme->btnFg),
            sqlString($mysqli,$args->theme->btnActBg),
            sqlString($mysqli,$args->theme->btnActFg),
            sqlString($mysqli,$args->theme->btnBdFg),
            sqlString($mysqli,$args->theme->btnBdW),
            sqlString($mysqli,$args->theme->btnShadow),
            sqlString($mysqli,$args->theme->inpBg),
            sqlString($mysqli,$args->theme->inpFg),
            sqlString($mysqli,$args->theme->inpActBg),
            sqlString($mysqli,$args->theme->inpActFg),
            sqlString($mysqli,$args->theme->inpBdFg),
            sqlString($mysqli,$args->theme->inpBdW),
            sqlString($mysqli,$args->theme->inpShadow),
            sqlString($mysqli,$args->theme->linkBg),
            sqlString($mysqli,$args->theme->linkFg),
            sqlString($mysqli,$args->theme->linkActBg),
            sqlString($mysqli,$args->theme->linkActFg)
        ]);
        dbDisonnect($mysqli);
        return new Reply($result?'ok': 'error', $result);
    }
}

?>
