<?php

require_once __DIR__ . '/../db/db.php';
require_once __DIR__ . '/../utils/send_reply.php';
require_once __DIR__ . '/../utils/verify_client_args.php';

if (verify_client_args($args, ['theme'])) {

    $db = db_open($args->key);

    $res = db_insert($db, 'themes', [        
    'name',
    'font',
    'left',
    'width',
    'vGap',
    'radius',
    'linkFg',
    'appBg',
    'barsBg',
    'barsFg',
    'barsBorder',
    'barsShadow',
    'tbarH',
    'tbarBold',
    'tbarItalic',
    'tbarFsize',
    'nbarH',
    'nbarBold',
    'nbarItalic',
    'nbarFsize',
    'nbarBgHi',
    'nbarFgHi',
    'fbarH',
    'fbarBold',
    'fbarItalic',
    'fbarFsize',
    'contBg',
    'contFg',
    'contW',
    'contBorder',
    'contShadow',
    'formBg',
    'formFg',
    'formBorder',
    'formShadow',
    'btnH',
    'btnBg',
    'btnFg',
    'btnBgHi',
    'btnFgHi',
    'btnBgDis',
    'btnFgDis',
    'btnBold',
    'btnItalic',
    'btnFsize',
    'btnShadow',
    'btnBorder',
    'inpH',
    'inpBg',
    'inpFg',
    'inpBgHi',
    'inpFgHi',
    'inpBgDis',
    'inpFgDis',
    'inpBold',
    'inpItalic',
    'inpFsize',
    'inpShadow',
    'inpBorder',
], [
    $args->name,
    $args->font,
    $args->left,
    $args->width,
    $args->vGap,
    $args->radius,
    $args->linkFg,
    $args->appBg,
    $args->barsBg,
    $args->barsFg,
    $args->barsBorder,
    $args->barsShadow,
    $args->tbarH,
    $args->tbarBold,
    $args->tbarItalic,
    $args->tbarFsize,
    $args->nbarH,
    $args->nbarBold,
    $args->nbarItalic,
    $args->nbarFsize,
    $args->nbarBgHi,
    $args->nbarFgHi,
    $args->fbarH,
    $args->fbarBold,
    $args->fbarItalic,
    $args->fbarFsize,
    $args->contBg,
    $args->contFg,
    $args->contW,
    $args->contBorder,
    $args->contShadow,
    $args->formBg,
    $args->formFg,
    $args->formBorder,
    $args->formShadow,
    $args->btnH,
    $args->btnBg,
    $args->btnFg,
    $args->btnBgHi,
    $args->btnFgHi,
    $args->btnBgDis,
    $args->btnFgDis,
    $args->btnBold,
    $args->btnItalic,
    $args->btnFsize,
    $args->btnShadow,
    $args->btnBorder,
    $args->inpH,
    $args->inpBg,
    $args->inpFg,
    $args->inpBgHi,
    $args->inpFgHi,
    $args->inpBgDis,
    $args->inpFgDis,
    $args->inpBold,
    $args->inpItalic,
    $args->inpFsize,
    $args->inpShadow,
    $args->inpBorder
]);

    if ($res === false) {
        send_reject('Misslyckade med att spara nytt tema');
    } else if (gettype($res) === 'string') {
        send_reject($res);
    } else {
        send_resolve(true);
    }
}
